name: Test Single Activity

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          TOKENS_JSON: ${{ secrets.TOKENS_JSON }}
          ACTIVITY_ID: ${{ secrets.ACTIVITY_ID }}
        run: |
          node scripts/fetch_single_activity.js

      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: activity-detail
          path: activity-detail.json
      
      - name: Upload photos
        uses: actions/upload-artifact@v4
        with:
          name: activity-photos
          path: activity-photos.json
      
      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
          git add data/activity-detail.json
          git add data/activity-photos.json
        
          git commit -m "Update activity data" || echo "No changes"
          git push   
